name: Release

on:
  push:
    branches: [main]
    paths:
      - '.changeset/**'
      - 'packages/**'
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
          
      - run: pnpm install --frozen-lockfile
      
      - name: Validate before release
        run: |
          pnpm validate:structure
          pnpm check:dependencies
          pnpm check:architecture
          pnpm lint
          pnpm test
          pnpm build
          pnpm size
      
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          version: pnpm changeset version
          commit: 'chore: release packages'
          title: 'chore: release packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Generate Release Notes
        if: steps.changesets.outputs.published == 'true'
        run: |
          echo "# 🚀 Release Published!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Published Packages:" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.changesets.outputs.publishedPackages }}" >> $GITHUB_STEP_SUMMARY
          
      - name: Create GitHub Release
        if: steps.changesets.outputs.published == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.changesets.outputs.version }}
          release_name: Release v${{ steps.changesets.outputs.version }}
          body: |
            ## 🎉 New Release
            
            ### Packages Released:
            ${{ steps.changesets.outputs.publishedPackages }}
            
            See [CHANGELOG](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
          draft: false
          prerelease: false